### model
model_name_or_path: model_path_to_DeepSeek-R1-Distill-Qwen-1.5B

### method
stage: sft
do_train: true
finetuning_type: full
lora_target: all
deepspeed: ./LLaMA-Factory/examples/deepspeed/ds_z2_config.json

### dataset
dataset: MELD_cot_train
eval_dataset: MELD_cot_valid
dataset_dir: base_dataset_dir
template: deepseek3
cutoff_len: 4096
max_samples: 10000000000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: your_output_dir
logging_steps: 50
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 5.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_steps: 20
fp16: true
ddp_timeout: 180000000

# eval
per_device_eval_batch_size: 2
eval_steps: 200
eval_strategy: steps
save_total_limit: 2